//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRepair
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarRepairEntities : DbContext
    {
        public CarRepairEntities()
            : base("name=CarRepairEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Detail> Detail { get; set; }
        public virtual DbSet<DetailRepair> DetailRepair { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<Repair> Repair { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Specialisation> Specialisation { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
