//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRepair
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailRepair
    {
        public int ID_DetailRepair { get; set; }
        public string RepairNote { get; set; }
        public int Detail_ID { get; set; }
        public int Count_Detail { get; set; }
        public int Repair_ID { get; set; }
        public int Employee_ID { get; set; }
    
        public virtual Detail Detail { get; set; }
        public virtual Repair Repair { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
